---
title: "職務・研究経歴書"
type: docs
---

<!-- TODO 研究概要編集 -->

## 要約

2017年10月九州大学大学院システム生命科学府生命医科学講座ゲノム医科学分野にて博士（理学）を取得。大学院在籍中の2016年6月から福岡歯科大学口腔歯学部口腔顔面美容医療センターにて臨時研究補助員として着任。破骨細胞の分離培養に関する研究を始めた。学位取得後の2018年1月には同研究センターにて特別研究員として就任し、同様の研究を実施。2018年6月九州大学大学院医学研究院細菌学分野にて学術研究員として着任し現在に至る。これまでの研究では次世代シーケンサから得られたゲノム配列情報をもとにした集団解析、及び統計解析を中心に行っている。

## 職務・研究経歴

2018年6月〜現在	学術研究員 (ポスト・ドクトラル・フェロー), 九州大学大学院医学研究院細菌学分野（指導：林哲也博士）
2016年6月〜2018年5月	臨時研究補助員・特別研究員 (ポスト・ドクトラル・フェロー), 福岡歯科大学口腔歯学部口腔顔面美容医療センター(指導:山下潤朗博士)

### 九州大学大学院医学研究院細菌学分野（2018年6月〜現在）

#### 研究テーマ1: *Serratia marcescens* (*S. marcescens*) とその近縁種のグローバルな集団構造と病院に適応した集団の同定

##### 研究概要

*S. marcescens*は、尿路感染症や菌血症など様々な日和見感染を引き起こし、時には院内感染を引き起こす重要な院内感染の原因菌である。近年の多剤耐性菌（MDR）の出現とその蔓延は、世界的に公衆衛生上に深刻な脅威となっている。本菌は自然環境中にも広く生息しているが、臨床分離株と環境分離株のゲノム上の相違は明らかになっておらず、*S. marcescens*とその近縁種のゲノムの違いも明らかでない。
そこで本研究では、今回新たに次世代シーケンサIllumina Miseqをつかって200株以上の臨床・環境株のシーケンスを実施。更に公開データベースに登録されていた*S. marcescens*とその近縁種（以下、”*S. marcescens* complex”と表記）配列データ合計775株を使った、*S. marcescens*を対象にしたゲノム解析では最大規模のゲノム解析を実施した。

##### 研究成果

*S. marcescens* complexの系統関係と複雑なグローバル集団構造が明らかになり、全ゲノムANIによって14のクレードで構成されることも明らかなった。14クレードのうち、クレード10、11、12、13はそれぞれ、*S. nematodiphila*、狭義の*S. marcescens*、*S. ureilytica*、*S. surfactantfaciens*に対応した。一部のクレードは他と明らかに異なるゲノムサイズとGC含量を有しており、この２つのゲノムパラメータには各クレード内でも負の相関が見られた。これらの特徴は可動性遺伝因子の獲得と関連しており、クレードごとの違いの出現には可動性遺伝因子の種類（プラスミド、プロファージ、他のintegrative elements）の違いが寄与していることが明らかになった。さらに重要な知見は、クレード1と2の大部分は臨床分離株や院内分離株であり、様々な基質特異性拡張型β-ラクタマーゼ遺伝子やカルバペネマーゼ遺伝子を含む幅広い抗菌薬耐性遺伝子とフルオロキノロン標的部位変異が蓄積されているため、高いMDR率を示すことである。この知見は、クレード1と2は*S. marcescens* complexの中で病院に適応した系統であることを示唆する。ただし、その潜在的な病原性の強さに関してはまだ不明である。本研究により、この細菌群の分類を再考するための重要なゲノム基盤に加え、各メンバーの進化、生物学的な特性、医療現場における病原性の違いに関する新たな知見が得られた。
この成果はMicrobial Genomics 2022年8巻3号にて共同第一著者で公開された。

#### 研究テーマ2: 大腸菌O103:H2を中心としたST17 complexの高精度ゲノム集団構造解析

##### 研究概要

腸管出血性大腸菌 (EHEC) 感染症は志賀毒素を産生する大腸菌を原因菌とし、腹痛や水様性の下痢、血便を病態として示す。 また発症後に合併症として溶血性尿毒症症候群や脳症を引き起こし重篤化することから注意すべき感染症の一つである。 EHEC感染症は毎年報告されており、分離される大腸菌の血清型は主にO157である。 O157以外の血清型も毎年一定数報告されており、報告数の多い順にO26、O111、O103と続く。 私は2007年から2018年に国内で分離された血清型O103:H2大腸菌103株について次世代シーケンサIllumina Miseqを用いてドラフトゲノムを作成し、データベース登録株と合わせて集団構造解析を実施したところ、同じ血清型にも関わらずゲノム構造がかなり異なる集団が存在していることを見出した。このことから、大腸菌の分類でよく使用されている血清型の範囲を超えた集団構造解析が必要であると考えた。
そこで、大腸菌の生存に必須な7つの遺伝子の遺伝子型の組み合わせで大腸菌の型別を行うMLST (Multi locus sequence typing) 法を基準とし、O103:H2の大部分が含まれるST17系統を中心とした株を収集し、非常に大規模な集団構造解析を実施することにした。
現在データベース株を含む約5000株のゲノム配列データを収集し解析が進行中である。

#### 研究テーマ3: 先進ゲノム支援プロジェクト

現在所属している研究室は、文部科学省科学研究費助成事業学術変革領域研究「学術研究支援基盤形成」先進ゲノム解析研究推進プラットフォーム先進ゲノム支援に参加しており、主にバクテリアを対象とした配列解析支援と情報解析支援を行っている。
私はこれまでに以下の研究課題に対しての情報解析支援を行った。

- 転写による染色体異常の発生メカニズム, 中川 拓郎先生, 大阪大学 (2022年度)
- 鉱山廃棄物の持続的な安定化に向けた有害金属の微生物ー鉱物相互作用の解明, 濱村 奈津子先生, 九州大学 (2021年度第1回)
- 培養技術とゲノム解析で紐解く硝化界のダークマター「完全アンモニア酸化細菌」, 藤谷 拓嗣先生, 中央大学 (2020年度第1回)
- 侵入害虫キムネクロナガハムシの生殖を操作する新規共生細菌の伝播メカニズムの解明, 高野 俊一郎先生, 九州大学 (2019年度)
- 巨大ウイルスが水圏低次生態系で果たす役割の包括的解明, 緒方 博之先生, 京都大学 (2018年度)
- 植物プランクトンと多様な菌類の寄生関係；変動環境下における感染症動態の解明, 鏡味 麻衣子先生, 横浜国立大学 (2018年度)
- 栄養バランス変化への適応能力を支える全身性シグナリングの解明, 服部 佑佳子先生, 京都大学 (2018年度)
- キネシンに依存しない双極性微小管形成機構の解明, 湯川 格史先生, 広島大学 (2018年度)

### 福岡歯科大学口腔歯学部口腔顔面美容医療センター (2016年6月〜2018年5月)

#### 研究テーマ1: 免疫システムにおける破骨細胞の役割

##### 研究概要

骨は造骨細胞と破骨細胞の機能によって年間10%も作り変えられている。
破骨細胞はマクロファージ系の細胞で骨の分解を行う。加えて免疫反応機構ももつ。
しかし破骨細胞は単離が難しく、免疫反応機構が解明されているわけではない。
骨基質に強固に付着するゾレドロン酸を添加すると破骨細胞を選択的に除去することができるが免疫系に深刻なダメージを与えることはできないことから破骨細胞を除去する方法では免疫反応における機能を推定することは難しい。
クロドロン酸を内包したリポソームを使用するとマクロファージを選択的に除去することが可能だがこちらも生体に深刻なダメージはない。
両方の試薬を同時に投与すると生体に深刻なダメージを与えることができる。
これらの試薬がどのように作用しているのか、特にゾレドロン酸の破骨細胞以外の免疫細胞に対する効果を検証する。

##### 研究成果

マウス骨髄を解剖により取り出し、得られた細胞群集に対してゾレドロン酸を添加。フローサイトメーターにてそれぞれの細胞量を計測するとマクロファージ、樹状細胞は現状し、血小板は増加傾向にあった。

#### 研究テーマ2: 造骨細胞が生成する細胞外マトリックスを骨にしていくためのメカニズム探索

##### 研究概要

骨が新たに成形されていくときに必須なのは造骨細胞。
細胞外マトリックスを生成し、それが骨へと変化していく。
実際に骨が成形されていく上でより骨生成を増強させるような要素は存在するのか調べる。
実験室内で作成された造骨細胞由来の細胞外マトリックスに骨生成に重要と思われるものを添加して骨生成の度合いが変化するのかを調べる。

### 九州大学大学院システム生命科学府生命医科学講座ゲノム医科学分野 (2012年4月〜2017年10月)

#### 研究テーマ: 末梢血由来DNAとEB不死化細胞由来DNAの遺伝子メチル化の変化解析

##### 研究概要

生活習慣に代表される環境要因と多数の遺伝子が、発症や症状などに複雑に関連している多因子疾患の解析が盛んに行われている。
環境要因の結果誘導されるDNAメチル化はゲノム修飾機構の一つであり、遺伝子発現を制御することで多因子疾患の感受性に関連していることが近年明らかになっている。
これまでヒトの遺伝子解析に利用されるDNAリソースとして末梢血細胞や唾液由来細胞、EB不死化細胞が一般的に使用されてきており、これらの細胞は遺伝子発現解析にも使用されている。
DNAメチル化は細胞の種類ごとに異なることがすでに知られており、これらの細胞ごとの状態の違いを知っておくことが今後の疾患解析に重要であると考えられた。
そこで、EB不死化細胞と末梢血細胞のゲノムワイドでのDNAメチル化状態を解析し、それぞれの細胞ごとの特徴を比較した。

##### 研究成果

EB不死化細胞を92サンプルと末梢血細胞の192サンプルを収集し、Human Methylation 450 K arrayを使用してヒトゲノム全体の約40万箇所のメチル化サイトの状態を調べた。
末梢血細胞に比べてEB不死化細胞では脱メチル化状態になっているメチル化サイトが多く、その多くが塩基配列のCGが偏在している領域 (CpG island) の外側に位置していた。
またCpG含量の低い遺伝子プロモータ領域にメチル化状態が変化しているサイトが偏在していることがわかった。組織特異的な遺伝子はCpG含量の低いプロモーター領域を持つことが多いことが知られていることから、細胞の種類ごとに特異的な遺伝子発現を制御している証拠を示すことができた。
加えて加齢とDNAメチル化状態が相関することが知られている2つのメチル化サイトについても比較したところ、EB不死化細胞ではその相関の程度が弱くなることがわかった。この要因として、EB不死化細胞はリンパ節細胞に対してEBウィルスを感染させることで不死化させ増殖能を獲得させているが、実験室では凍結融解や培養を繰り返しているため、徐々にDNAメチル化状態への影響が蓄積したのではないかと考えている。
この成果はHuman Genomics 2017年11巻1号にて第一著者で公開された。

## 経験・知識

- 自宅でNASサーバーを運用

### 主要サイトURL

Github: https://github.com/itTan-git
researchmap: https://researchmap.jp/it_taniguchi
LinkedIn: https://www.linkedin.com/in/%E6%84%9B%E6%A8%B9-%E8%B0%B7%E5%8F%A3-5371aab4/
Google Scholar Citations: https://scholar.google.com/citations?user=XgKotgcAAAAJ
ResearchGate: https://www.researchgate.net/profile/Itsuki-Taniguchi

## 習得技術

## 資格・語学力・ITスキル

- TOEIC 775点 (2016年6月)
- バイオインフォマティクス・データ解析 (10年間)
- マイクロアレイ解析 (使用言語: R レベル 4、5年間)
- 次世代シーケンサ解析 (使用言語: R レベル 4、5年間)
- サーバー管理(CentOS 7) (3年間)

## 使用機器

- 次世代シーケンサ
- フローサイトメーター
- サンガーシーケンサー
- サーマルサイクラー
- 

## 取り扱い経験のある生物

- マウス
- マウス骨髄細胞
- RAW264.7 (マウスマクロファージ細胞株)
- ハブ
- 大腸菌

## 保持している技術

### 実験技術

- マウス実験(解剖・移植)
- 凍結切片作成
- ハブの毒腺抽出
- クローニング
- DNA抽出
- 第3世代シーケンサ (Nanopore) 用長鎖DNA調整

### ゲノム解析技術

- 細菌の新規ゲノム配列決定
- メタゲノム解析
- RNAseq解析

### バイオインフォマティクス技術

- マイクロアレイ解析

## 自己PR

- Rは当初独学で勉強を始め、現在では論文作成用の解析はほぼ全てRをベースに行うことができるようになりました。常に最新の情報を得るように心がけており、コミュニティにも参加して積極的に学習を続けています。
- 先進ゲノム支援プロジェクトでは様々な分野の先生方の研究課題を解決するために密なコミュニケーションを心がけて来ました。そのおかげかいくつかのプロジェクトについては非常に学術的にインパクトのある結果を得ることができています。
- データ解析については非常に丁寧に行うことを心がけており、解析結果や試行錯誤した点については都度文章化・マニュアル化をするように意識していました。作成したマニュアルによって研究室全体の解析技術の向上に貢献できたと考えています。
